export let db_games_eng = [
  {
    id: 1,
    name: 'Bingo Lottery',
    description:
      'In Bingo Lotteries, combinations of numbers in a ticket have already been generated. You will be a winner if the numbers on your ticket match the numbers generated by the random number generator.',
    divStyle: {
      backgroundIMG: 'url(star.png)'
    }
  },
  {
    id: 2,
    name: 'Instant Лottery',
    description:
      'Instant lotteries came into being thanks to two programmers from Massachusetts. To find out if you have a winning ticket, you need to erase the protective layer.',
    divStyle: {},
  },
  {
    id: 3,
    name: 'Numerical Lottery',
    description:
      'In number lotteries, the participant forms the combination by marking the numbers on the ticket. Drawings are carried out with the help of a random number generator.',
    divStyle: {},
  },
]

export let db_games_rus = [
  {
    id: 31,
    name: 'Бинго Лотерея>',
    description:
      'В бинго-лотереях комбинации чисел в билете уже сформированы. Вы станете победителем, если числа в вашем билете совпадут с номерами сгенерированными генератором случайных чисел.',
    divStyle: {},
  },
  {
    id: 32,
    name: 'Моментальная Лотерея',
    description:
      'Моментальные лотереи появились благодаря двум программистам из Массачусетса. Чтобы узнать, выигрышный ли у вас билет, нужно стереть защитный слой.',
    divStyle: {},
  },
  {
    id: 33,
    name: 'Числовая Лотерея',
    description:
      'В числовых лотереях участник сам формирует комбинацию, отмечая числа в билете. Розыгрыши проводят с помощью генератора случайныых чисел. По этой схеме работают, например: "Спортлото".',
    divStyle: {},
  },
]
